language: node_js
sudo: required
node_js:
  - '14.21.3'

notifications:
  slack: focallocal:njis5lKnuOTF1dp8W7HiTn8I

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential manpages-dev
  - wget http://ftp.gnu.org/gnu/libc/glibc-2.28.tar.gz
  - tar -xvzf glibc-2.28.tar.gz
  - cd glibc-2.28
  - mkdir build
  - cd build
  - ../configure --prefix=/opt/glibc-2.28
  - make -j$(nproc)
  - sudo make install
  - export LD_LIBRARY_PATH=/opt/glibc-2.28/lib:$LD_LIBRARY_PATH
  - cd ../../

branches:
  only:
    - master
    - deploy-btm
    - deploy-phm

script:
  - npm install
  - mup setup
  - mup deploy
