language: node_js
sudo: required
node_js:
  - '8.11.1'

notifications:
  slack: focallocal:njis5lKnuOTF1dp8W7HiTn8I

cache:
  directories:
    - $HOME/.meteor

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Remove cache if the project is upgraded to a newer version of meteor
  - export PATH="$HOME/.meteor:$PATH"
  - echo "$sops_gpg_key" | base64 -d | gpg --batch --import
  - cd deployment/$(./deployment/branch-to-dir.sh "$TRAVIS_BRANCH")
  - for file in *.enc*; do sops --decrypt --output "${file%.enc*}${file##*.enc}" "${file}"; done
  - npm install -g mup
  - curl https://install.meteor.com/?release=1.6.1.1 | /bin/sh

branches:
  only:
    - master
    - fl-sleeper
    - master_withoutDCS
    - deploy-btm
    - deploy-phm

script:
  #- npm test
  - mup setup
  - mup deploy
